package database;

import entity.Dare;

import java.sql.*;

/**
 * Dare communication to Dare table in database
 *
 * @author julia
 */
public class DareTable {

    /**
     * Build String request for database
     *
     * @param objectiveType variable in dare
     * @param objective
     * @param scopeType     variable in dare
     * @param scopeLength   number of days dare will be
     * @param start         date when dare start
     * @param end           date when dare will end
     */
    public static int insertNewDareToDB(String objectiveType, String objective, String scopeType,
                                        int scopeLength, String start, String end) {
        String request1 = "INSERT INTO dare(ObjectiveType, Objective, ScopeType, ScopeLength ";
        String request2 = ",Start, End) VALUES ('" + objectiveType + "', '" + objective + "', '" + scopeType + "', '";
        String request3 = scopeLength + "','" + start + "','" + end + "');";
        String fullRequest = request1 + request2 + request3;
        int dareId = insertToDare(fullRequest);
        return dareId;
    }

    /**
     * connect to database and make request to addNewDare. Result returns autogenerated key.
     *
     * @param request String containing full SQL request
     */
    public static int insertToDare(String request) {
        int dareId = 0;

        Connection conn = null;
        Statement statement = null;
        ResultSet resultFromQuery = null;

        try {
            Class.forName("org.sqlite.JDBC");
            String path = "jdbc:sqlite:lib/dare_n_share.db";
            conn = DriverManager.getConnection(path);

            statement = conn.createStatement();
            statement.execute(request);
            resultFromQuery = statement.getGeneratedKeys();

            while (resultFromQuery.next()) {
                dareId = resultFromQuery.getInt(1);
                System.out.println(dareId);
            }

        } catch (SQLException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        } finally {
            try { if (resultFromQuery != null) resultFromQuery.close(); } catch (Exception e) {}
            try { if (statement != null) statement.close(); } catch (Exception e) {}
            try { if (conn != null) conn.close(); } catch (Exception e) {}
        }

        return dareId;
    }


    /**
     * retrieves information from specific dare using dareId in table and returns dare object
     *
     * FIXME: bör detta verkligen se ut så här?
     *
     * @param dareId
     */
    public static Dare getDareFromDB(int dareId) {

        Connection conn = null;
        Statement statement = null;
        ResultSet resultFromQuery = null;

        Dare dare = new Dare();

        try {
            Class.forName("org.sqlite.JDBC");
            String path = "jdbc:sqlite:lib/dare_n_share.db";
            conn = DriverManager.getConnection(path);

            String query = "SELECT * FROM Dare where Dareid =" + dareId + ";";
            assert conn != null;

            statement = conn.createStatement();
            statement.execute(query);
            resultFromQuery = statement.getResultSet();

            while (resultFromQuery.next()) {
                String objectiveType = resultFromQuery.getString("ObjectiveType");

                String objectiveGoal = resultFromQuery.getString("Objective");

                //Gets Scope
                String scopeType = resultFromQuery.getString("ScopeType");
                int scopeLength = resultFromQuery.getInt("ScopeLength");

                //Gets start and end date
                String start = resultFromQuery.getString("Start");
                String end = resultFromQuery.getString("End");

                //Sets dare value
                dare.setObjectiveFromDB(objectiveType, objectiveGoal);
                dare.setScopeFromDB(scopeType, scopeLength);
                dare.setStartDate(start);
                dare.setEndDate(end);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try { if (resultFromQuery != null) resultFromQuery.close(); } catch (Exception e) {}
            try { if (statement != null) statement.close(); } catch (Exception e) {}
            try { if (conn != null) conn.close(); } catch (Exception e) {}
        }

        return dare;
    }


}
