package database;

import java.sql.*;

/**
 * Dare communication to Dare table in database
 * For all in code review : query or request? note to self
 *
 * @author julia
 */

public class DareTable {



    /**
     * Build String request for database
     *
     * @param objectiveType variable in dare
     * @param objective
     * @param scopeType     variable in dare
     * @param scopeLength   number of days dare will be
     * @param start         date when dare start
     * @param end           date when dare will end
     */
    public static int insertNewDareToDB(String objectiveType, String objective, String scopeType,
                                  int scopeLength, String start, String end) {
        String request1 = "INSERT INTO dare(ObjectiveType, Objective, ScopeType, ScopeLength ";
        String request2 = ",Start, End) VALUES ('" + objectiveType + "', '" + objective + "', '" + scopeType + "', '";
        String request3 = scopeLength + "','" + start + "','" + end + "');";
        String fullRequest = request1 + request2 + request3;
        int dareId = insertToDare(fullRequest);
        return dareId;
    }

    /**
     * connect to database and make request to addNewDare. Result returns autogenerated key.
     *
     * @param request String containing full SQL request ? kan man skriva så?
     */
    public static int insertToDare(String request) {
        int dareId = 0;
        Connection connect = null;
        try {
            Class.forName("org.sqlite.JDBC");
            String path = "jdbc:sqlite:lib/dare_n_share.db";
            connect = DriverManager.getConnection(path);
            System.out.println("Connection ok");

            Statement statement = connect.createStatement();
            statement.execute(request);
            ResultSet result = statement.getGeneratedKeys();

            while (result.next()) {
                dareId = result.getInt(1);
                System.out.println(dareId);
            }
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        return dareId;
    }


    /**
     * retrieves information from specific dare and store in variables
     *
     * @param dareId
     */
    public static ResultSet getDareFromDB(int dareId) {

        Connection conn = null;
        ResultSet resultFromQuery = null;
        try {
            Class.forName("org.sqlite.JDBC");
            String path = "jdbc:sqlite:lib/dare_n_share.db";
            conn = DriverManager.getConnection(path);
            System.out.println("Connection ok");


            String query = "SELECT * FROM Dare where Dareid =" + dareId + ";";
            assert conn != null;
            Statement statement = conn.createStatement();

            statement.execute(query);
            resultFromQuery = statement.getResultSet();

        }catch(Exception e){
            e.printStackTrace();
        }
            return resultFromQuery;

    }


}
